version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=medical-app
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '6432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
