services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    networks:
      - postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:12-alpine
    networks:
      - postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '6543:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  postgres:
    driver: bridge
